# Generated by Django 4.1.7 on 2023-03-18 03:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_car', models.CharField(max_length=255)),
                ('model_technique', models.CharField(max_length=255)),
                ('model_engine', models.CharField(max_length=255)),
                ('number_engine', models.CharField(max_length=255)),
                ('model_transmission', models.CharField(max_length=255)),
                ('number_transmission', models.CharField(max_length=255)),
                ('model_driving_bridge', models.CharField(max_length=255)),
                ('number_driving_bridge', models.CharField(max_length=255)),
                ('model_controlled_bridge', models.CharField(max_length=255)),
                ('number_controlled_bridge', models.CharField(max_length=255)),
                ('delivery_contract_number', models.CharField(max_length=255)),
                ('date_of_shipment_from_the_factory', models.DateField(auto_now=True)),
                ('consignee', models.CharField(max_length=255)),
                ('delivery_address', models.CharField(max_length=255)),
                ('equipment', models.CharField(max_length=255)),
                ('client', models.CharField(max_length=255)),
                ('service_company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_maintenance', models.CharField(max_length=255)),
                ('date_of_maintenance', models.DateField(auto_now_add=True)),
                ('operating_time', models.DateField(auto_now=True)),
                ('order_number', models.CharField(max_length=255)),
                ('date_of_the_order_order', models.DateField(auto_now=True)),
                ('the_organization_that_conducted', models.CharField(max_length=255)),
                ('car', models.CharField(max_length=255)),
                ('service_company', models.CharField(max_length=255)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapps.guide')),
            ],
        ),
        migrations.CreateModel(
            name='GuideCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapps.car')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapps.guide')),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_refusal', models.DateField(auto_now_add=True)),
                ('operating_time', models.DateField(auto_now_add=True)),
                ('failure_node', models.CharField(max_length=255)),
                ('description_of_the_failure', models.CharField(max_length=255)),
                ('recovery_method', models.CharField(max_length=255)),
                ('spare_parts_used', models.CharField(max_length=255)),
                ('date_of_restoration', models.DateField(auto_now_add=True)),
                ('equipment_downtime', models.FloatField(default=0.0)),
                ('car', models.CharField(max_length=255)),
                ('service_company', models.CharField(max_length=255)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapps.guide')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='guide',
            field=models.ManyToManyField(through='mainapps.GuideCar', to='mainapps.guide'),
        ),
    ]
